In [1]:
import numpy as np
import pandas as pd 
import statsmodels.api as sm
import statsmodels.formula.api as smf
import seaborn as sns
from sklearn.preprocessing import scale 
from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
from sklearn.metrics import roc_auc_score,roc_curve
import statsmodels.formula.api as smf
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn import tree

from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import SVC

from warnings import filterwarnings
filterwarnings('ignore')

from sklearn import metrics
from sklearn.tree import plot_tree
import matplotlib.pyplot as plt
from skompiler import skompile

In [2]:
df = pd.read_csv("hmelq.csv")
df.head(5)

,bad,loan,mortdue,value,reason,job,yoj,derog,delinq,clage,ninq,clno,debtinc
0,0,81200,18834.0,108355.0,HomeImp,NaN,28.0,0.0,0.0,139.14,0.0,14.0,34.042
1,0,12600,103960.0,127384.0,DebtCon,NaN,2.0,0.0,0.0,129.02,0.0,25.0,34.479
2,0,18000,46865.0,61266.0,DebtCon,NaN,5.0,0.0,0.0,102.59,2.0,9.0,26.354
3,0,10300,57676.0,71027.0,DebtCon,NaN,19.0,0.0,0.0,157.52,1.0,11.0,33.992
4,0,9400,56508.0,78358.0,DebtCon,NaN,17.0,0.0,0.0,141.93,0.0,11.0,32.327

In [3]:
df.dropna(inplace = True)

In [4]:
df_dummies = pd.get_dummies(df)

# SVC

In [5]:
X = df_dummies.drop("bad", axis = 1)
y = df_dummies["bad"]
X_train , X_test, y_train, y_test = train_test_split(X, y , test_size = 0.25, random_state = 42)

In [6]:
svc = SVC()

In [7]:
svc_model = svc.fit(X_train, y_train)
y_pred = svc_model.predict(X_test)

ac = accuracy_score(y_test, y_pred)
con_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

In [8]:
accuracy_score(y_test, y_pred)

0.9227722772277228

In [9]:
confusion_matrix(y_test, y_pred)

array([[466,   0],
       [ 39,   0]], dtype=int64)

In [10]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.92      1.00      0.96       466
           1       0.00      0.00      0.00        39

    accuracy                           0.92       505
   macro avg       0.46      0.50      0.48       505
weighted avg       0.85      0.92      0.89       505

In [11]:
svc_model

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [21]:
svc_params = {"kernel": ["linear", 'poly', 'rbf'],
             "C": [1,2,3,6,8]}

In [22]:
svc_model_cv = GridSearchCV(svc, svc_params, cv=5, n_jobs= -1, verbose= 2)

In [23]:
svc_model_cv.fit(X_train, y_train)

Fitting 5 folds for each of 15 candidates, totalling 75 fits

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  33 tasks      | elapsed:  8.3min
[Parallel(n_jobs=-1)]: Done  75 out of  75 | elapsed: 20.4min finished

GridSearchCV(cv=5, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=-1,
             param_grid={'C': [1, 2, 3, 6, 8],
                         'kernel': ['linear', 'poly', 'rbf']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=2)

In [24]:
svc_model_cv.best_params_

{'C': 8, 'kernel': 'linear'}

In [13]:
svc_model = SVC(C = 8, kernel = "linear")
svc_model_tuned = svc_model.fit(X_train, y_train)

In [14]:
y_pred_tuned = svc_model_tuned.predict(X_test)

ac_tuned = accuracy_score(y_test, y_pred_tuned)
con_matrix_tuned = confusion_matrix(y_test, y_pred_tuned) 
class_report_tuned = classification_report(y_test, y_pred_tuned)


print("Accuracy Score: {} \nConfusion Matrix: \n{}\n*********************************\nClassification Report\n{}\n\n <--------------------------------------->\n\n\nAccuracy Score Tuned: {} \nConfusion Matrix Tuned: \n{}\n*********************************\nClassification Report Tuned\n{} ".format(ac,con_matrix, class_report, ac_tuned, con_matrix_tuned, class_report_tuned))

Accuracy Score: 0.9227722772277228
Confusion Matrix:
[[466   0]
 [ 39   0]]
*********************************
Classification Report
              precision    recall  f1-score   support

           0       0.92      1.00      0.96       466
           1       0.00      0.00      0.00        39

    accuracy                           0.92       505
   macro avg       0.46      0.50      0.48       505
weighted avg       0.85      0.92      0.89       505


 <--------------------------------------->


Accuracy Score Tuned: 0.9267326732673268
Confusion Matrix Tuned:
[[466   0]
 [ 37   2]]
*********************************
Classification Report Tuned
              precision    recall  f1-score   support

           0       0.93      1.00      0.96       466
           1       1.00      0.05      0.10        39

    accuracy                           0.93       505
   macro avg       0.96      0.53      0.53       505
weighted avg       0.93      0.93      0.90       505

# XG Boost

In [64]:
X = df_dummies.drop("bad", axis = 1)
y = df_dummies["bad"]
X_train , X_test, y_train, y_test = train_test_split(X, y , test_size = 0.25, random_state = 42)

In [65]:
xgb = XGBClassifier()

In [66]:
xgb_model = xgb.fit(X_train, y_train)

In [67]:
y_pred = xgb_model.predict(X_test)

ac = accuracy_score(y_test, y_pred)
con_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

In [68]:
accuracy_score(y_test, y_pred)

0.9663366336633663

In [69]:
confusion_matrix(y_test, y_pred)

array([[465,   1],
       [ 16,  23]], dtype=int64)

In [70]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.97      1.00      0.98       466
           1       0.96      0.59      0.73        39

    accuracy                           0.97       505
   macro avg       0.96      0.79      0.86       505
weighted avg       0.97      0.97      0.96       505

In [57]:
xgb_params = {
        'min_child_weight': [0.8 ,0.9, 1],
        'gamma': [0.5, 1, 1.5, 2, 5],
        'subsample': [0.6, 0.8, 1.0],
        'colsample_bytree': [0.6, 0.8, 1.0],
        'max_depth': [3, 4, 5]
        }

In [58]:
xgb_model_cv = GridSearchCV(xgb, xgb_params, cv = 5, n_jobs=-1 , verbose= 2)

In [59]:
xgb_model_cv.fit(X_train, y_train)

Fitting 5 folds for each of 405 candidates, totalling 2025 fits

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  33 tasks      | elapsed:    2.0s
[Parallel(n_jobs=-1)]: Done 272 tasks      | elapsed:    8.7s
[Parallel(n_jobs=-1)]: Done 678 tasks      | elapsed:   19.5s
[Parallel(n_jobs=-1)]: Done 1244 tasks      | elapsed:   37.1s
[Parallel(n_jobs=-1)]: Done 1974 tasks      | elapsed:  1.0min
[Parallel(n_jobs=-1)]: Done 2018 out of 2025 | elapsed:  1.1min remaining:    0.1s
[Parallel(n_jobs=-1)]: Done 2025 out of 2025 | elapsed:  1.1min finished

GridSearchCV(cv=5, error_score=nan,
             estimator=XGBClassifier(base_score=0.5, booster='gbtree',
                                     colsample_bylevel=1, colsample_bynode=1,
                                     colsample_bytree=1, gamma=0, gpu_id=-1,
                                     importance_type='gain',
                                     interaction_constraints='',
                                     learning_rate=0.300000012,
                                     max_delta_step=0, max_depth=6,
                                     min_child_weight=1, missing=nan,
                                     monotone_constraints='()',
                                     n_estimators=100, n_job...
                                     random_state=0, reg_alpha=0, reg_lambda=1,
                                     scale_pos_weight=1, subsample=1,
                                     tree_method='exact', validate_parameters=1,
                                     verbosity=None),
             iid='deprecated', n_jobs=-1,
             param_grid={'colsample_bytree': [0.6, 0.8, 1.0],
                         'gamma': [0.5, 1, 1.5, 2, 5], 'max_depth': [3, 4, 5],
                         'min_child_weight': [0.8, 0.9, 1],
                         'subsample': [0.6, 0.8, 1.0]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=2)

In [60]:
xgb_model_cv.best_params_

{'colsample_bytree': 0.6,
 'gamma': 0.5,
 'max_depth': 5,
 'min_child_weight': 0.8,
 'subsample': 0.6}

In [76]:
xgb_model_tuned = XGBClassifier(colsample_bytree = 0.6, gamma = 0.5, max_depth =5, min_child_weight = 0.8, subsample = 0.6).fit(X_train, y_train)
y_pred_tuned = xgb_model_tuned.predict(X_test)


ac_tuned = accuracy_score(y_test, y_pred_tuned)
con_matrix_tuned = confusion_matrix(y_test, y_pred_tuned) 
class_report_tuned = classification_report(y_test, y_pred_tuned)


print("Accuracy Score: {} \nConfusion Matrix: \n{}\n*********************************\nClassification Report\n{}\n\n <--------------------------------------->\n\n\nAccuracy Score Tuned: {} \nConfusion Matrix Tuned: \n{}\n*********************************\nClassification Report Tuned\n{} ".format(ac,con_matrix, class_report, ac_tuned, con_matrix_tuned, class_report_tuned))

Accuracy Score: 0.9663366336633663
Confusion Matrix:
[[465   1]
 [ 16  23]]
*********************************
Classification Report
              precision    recall  f1-score   support

           0       0.97      1.00      0.98       466
           1       0.96      0.59      0.73        39

    accuracy                           0.97       505
   macro avg       0.96      0.79      0.86       505
weighted avg       0.97      0.97      0.96       505


 <--------------------------------------->


Accuracy Score Tuned: 0.9544554455445544
Confusion Matrix Tuned:
[[464   2]
 [ 21  18]]
*********************************
Classification Report Tuned
              precision    recall  f1-score   support

           0       0.96      1.00      0.98       466
           1       0.90      0.46      0.61        39

    accuracy                           0.95       505
   macro avg       0.93      0.73      0.79       505
weighted avg       0.95      0.95      0.95       505

# Knn C

In [44]:
knnc = KNeighborsClassifier()
knnc_model = knnc.fit(X_train, y_train)
y_pred = knnc_model.predict(X_test)

ac = accuracy_score(y_test, y_pred)
con_matrix = confusion_matrix(y_test, y_pred) 
class_report = classification_report(y_test, y_pred)


print("Accuracy Score: {} \nConfusion Matrix: {}\n*********************************\nClassification Report\n  {}".format(ac,con_matrix, class_report))

Accuracy Score: 0.9227722772277228
Confusion Matrix: [[462   4]
 [ 35   4]]
*********************************
Classification Report
                precision    recall  f1-score   support

           0       0.93      0.99      0.96       466
           1       0.50      0.10      0.17        39

    accuracy                           0.92       505
   macro avg       0.71      0.55      0.56       505
weighted avg       0.90      0.92      0.90       505

In [45]:
knnc_params = {"n_neighbors": np.arange(2,20)}

In [46]:
knnc_model_cv = GridSearchCV(knnc, knnc_params, n_jobs = -1, verbose = 2)
knnc_model_cv.fit(X_train, y_train)
knnc_model_cv.best_params_

Fitting 5 folds for each of 18 candidates, totalling 90 fits

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  38 tasks      | elapsed:    1.9s
[Parallel(n_jobs=-1)]: Done  90 out of  90 | elapsed:    2.2s finished

{'n_neighbors': 14}

In [75]:
knnc_tuned = KNeighborsClassifier(n_neighbors= 14)
knnc_model_tuned = knnc_tuned.fit(X_train, y_train)
y_pred_tuned = knnc_model_tuned.predict(X_test)

ac_tuned = accuracy_score(y_test, y_pred_tuned)
con_matrix_tuned = confusion_matrix(y_test, y_pred_tuned) 
class_report_tuned = classification_report(y_test, y_pred_tuned)


print("Accuracy Score: {} \nConfusion Matrix: \n{}\n*********************************\nClassification Report\n{}\n\n <--------------------------------------->\n\n\nAccuracy Score Tuned: {} \nConfusion Matrix Tuned: \n{}\n*********************************\nClassification Report Tuned\n{} ".format(ac,con_matrix, class_report, ac_tuned, con_matrix_tuned, class_report_tuned))

Accuracy Score: 0.9663366336633663
Confusion Matrix:
[[465   1]
 [ 16  23]]
*********************************
Classification Report
              precision    recall  f1-score   support

           0       0.97      1.00      0.98       466
           1       0.96      0.59      0.73        39

    accuracy                           0.97       505
   macro avg       0.96      0.79      0.86       505
weighted avg       0.97      0.97      0.96       505


 <--------------------------------------->


Accuracy Score Tuned: 0.9267326732673268
Confusion Matrix Tuned:
[[466   0]
 [ 37   2]]
*********************************
Classification Report Tuned
              precision    recall  f1-score   support

           0       0.93      1.00      0.96       466
           1       1.00      0.05      0.10        39

    accuracy                           0.93       505
   macro avg       0.96      0.53      0.53       505
weighted avg       0.93      0.93      0.90       505

# Naive Bayes Finans datası

In [43]:
df = pd.read_excel('HW_Data_Set.xlsx', index_col=None)

In [44]:
df.head()

,ind_5,ind_6,ind_8,ind_9,ind_10,ind_12,ind_13,ind_14,ind_15,ind_16,...,ind_416,ind_418,ind_420,ind_422,ind_424,ind_426,ind_428,20_target,50_target,90_target
0,19,17,100.0,85.714286,14.285714,72.363515,60.808814,23.80,17.62,11.73,...,-49.6,-54,-152,-353,1.0,0.498547,0.701906,15.135802,35.625252,36.997753
1,24,19,100.0,78.571429,21.428571,74.275883,64.366798,11.45,18.16,12.22,...,-55.6,-60,-158,-359,1.0,0.537088,0.690833,15.143348,35.643013,37.016198
2,30,24,100.0,71.428571,28.571429,75.140402,65.915803,8.75,17.86,12.28,...,-58.4,-60,-160,-362,1.0,0.615169,0.693040,15.146870,35.651301,-37.024805
3,37,30,100.0,64.285714,35.714286,76.677846,68.584234,7.80,14.76,12.61,...,-61.8,-65,-166,-367,1.0,0.661517,0.673418,15.153283,0.000000,-37.040483
4,41,37,100.0,57.142857,42.857143,81.603007,76.455495,14.90,11.92,14.25,...,-79.8,-86,-186,-388,1.0,0.747204,0.700522,-15.179065,-35.727079,-37.103503

In [45]:
target_obj_20=[]

for i in df['20_target']: 
    
    if i == 0 :
    
        target_obj_20.append(1)
    
    elif i < 0: 
    
        target_obj_20.append(0)
        
    else :
        
        target_obj_20.append(2)

df['target_obj_20'] = target_obj_20          

target_obj_50=[]

for i in df['50_target']: 
    
    if i == 0 :
    
        target_obj_50.append(1)
    
    elif i < 0: 
    
        target_obj_50.append(0)
        
    else :
        
        target_obj_50.append(2)
    
df['target_obj_50'] = target_obj_50  


target_obj_90=[]

for i in df['90_target']: 
    
    if i == 0 :
    
        target_obj_90.append(1)
    
    elif i < 0: 
    
        target_obj_90.append(0)
        
    else :
        
        target_obj_90.append(2)
    
df['target_obj_90'] = target_obj_90

In [46]:
df.head()

,ind_5,ind_6,ind_8,ind_9,ind_10,ind_12,ind_13,ind_14,ind_15,ind_16,...,ind_422,ind_424,ind_426,ind_428,20_target,50_target,90_target,target_obj_20,target_obj_50,target_obj_90
0,19,17,100.0,85.714286,14.285714,72.363515,60.808814,23.80,17.62,11.73,...,-353,1.0,0.498547,0.701906,15.135802,35.625252,36.997753,2,2,2
1,24,19,100.0,78.571429,21.428571,74.275883,64.366798,11.45,18.16,12.22,...,-359,1.0,0.537088,0.690833,15.143348,35.643013,37.016198,2,2,2
2,30,24,100.0,71.428571,28.571429,75.140402,65.915803,8.75,17.86,12.28,...,-362,1.0,0.615169,0.693040,15.146870,35.651301,-37.024805,2,2,0
3,37,30,100.0,64.285714,35.714286,76.677846,68.584234,7.80,14.76,12.61,...,-367,1.0,0.661517,0.673418,15.153283,0.000000,-37.040483,2,1,0
4,41,37,100.0,57.142857,42.857143,81.603007,76.455495,14.90,11.92,14.25,...,-388,1.0,0.747204,0.700522,-15.179065,-35.727079,-37.103503,0,0,0

In [47]:
df.drop(["20_target", "50_target", "90_target"],axis = 1, inplace = True)

In [48]:
df.head(2)

,ind_5,ind_6,ind_8,ind_9,ind_10,ind_12,ind_13,ind_14,ind_15,ind_16,...,ind_416,ind_418,ind_420,ind_422,ind_424,ind_426,ind_428,target_obj_20,target_obj_50,target_obj_90
0,19,17,100.0,85.714286,14.285714,72.363515,60.808814,23.80,17.62,11.73,...,-49.6,-54,-152,-353,1.0,0.498547,0.701906,2,2,2
1,24,19,100.0,78.571429,21.428571,74.275883,64.366798,11.45,18.16,12.22,...,-55.6,-60,-158,-359,1.0,0.537088,0.690833,2,2,2

In [49]:
df

,ind_5,ind_6,ind_8,ind_9,ind_10,ind_12,ind_13,ind_14,ind_15,ind_16,...,ind_416,ind_418,ind_420,ind_422,ind_424,ind_426,ind_428,target_obj_20,target_obj_50,target_obj_90
0,19,17,100.000000,85.714286,14.285714,72.363515,60.808814,23.80,17.62,11.73,...,-49.6,-54,-152,-353,1.000000,0.498547,0.701906,2,2,2
1,24,19,100.000000,78.571429,21.428571,74.275883,64.366798,11.45,18.16,12.22,...,-55.6,-60,-158,-359,1.000000,0.537088,0.690833,2,2,2
2,30,24,100.000000,71.428571,28.571429,75.140402,65.915803,8.75,17.86,12.28,...,-58.4,-60,-160,-362,1.000000,0.615169,0.693040,2,2,0
3,37,30,100.000000,64.285714,35.714286,76.677846,68.584234,7.80,14.76,12.61,...,-61.8,-65,-166,-367,1.000000,0.661517,0.673418,2,1,0
4,41,37,100.000000,57.142857,42.857143,81.603007,76.455495,14.90,11.92,14.25,...,-79.8,-86,-186,-388,1.000000,0.747204,0.700522,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6162,27,31,57.142857,28.571429,28.571429,60.010531,32.362582,9.70,9.38,13.66,...,-28.2,-40,-11,-270,0.270270,0.840000,0.600846,2,0,0
6163,22,27,50.000000,21.428571,28.571429,60.209998,32.914628,7.65,8.84,11.79,...,-28.6,-41,-12,-271,0.000000,0.737470,0.527673,2,0,0
6164,19,22,42.857143,14.285714,28.571429,64.329611,43.550592,8.95,9.06,10.30,...,-37.2,-49,-21,-280,0.769231,0.632107,0.551759,0,0,0
6165,19,19,100.000000,7.142857,92.857143,69.027764,54.130755,13.55,10.36,10.55,...,-48.9,-61,-33,-292,1.000000,0.733010,0.591584,0,0,0
6166,19,19,92.857143,0.000000,92.857143,65.157180,45.524973,11.45,10.16,9.68,...,-44.0,-56,-28,-288,1.000000,0.687500,0.593936,0,0,0

In [50]:
df['ind_420'] = pd.to_numeric(df['ind_420'], errors='coerce')
df['ind_422'] = pd.to_numeric(df['ind_422'], errors='coerce')

In [51]:
df["ind_422"].fillna(df["ind_422"].median(), inplace=True)
df["ind_420"].fillna(df["ind_420"].median(), inplace=True)

In [52]:
df_dummies2 = pd.get_dummies(df['ind_109'])
df_dummies = df.drop('ind_109', axis = 1)

df_dummies = pd.concat([df_dummies, df_dummies2], axis=1, sort=False)

In [53]:
df_dummies

,ind_5,ind_6,ind_8,ind_9,ind_10,ind_12,ind_13,ind_14,ind_15,ind_16,...,ind_420,ind_422,ind_424,ind_426,ind_428,target_obj_20,target_obj_50,target_obj_90,GREEN,RED
0,19,17,100.000000,85.714286,14.285714,72.363515,60.808814,23.80,17.62,11.73,...,-152.0,-353.0,1.000000,0.498547,0.701906,2,2,2,1,0
1,24,19,100.000000,78.571429,21.428571,74.275883,64.366798,11.45,18.16,12.22,...,-158.0,-359.0,1.000000,0.537088,0.690833,2,2,2,1,0
2,30,24,100.000000,71.428571,28.571429,75.140402,65.915803,8.75,17.86,12.28,...,-160.0,-362.0,1.000000,0.615169,0.693040,2,2,0,1,0
3,37,30,100.000000,64.285714,35.714286,76.677846,68.584234,7.80,14.76,12.61,...,-166.0,-367.0,1.000000,0.661517,0.673418,2,1,0,1,0
4,41,37,100.000000,57.142857,42.857143,81.603007,76.455495,14.90,11.92,14.25,...,-186.0,-388.0,1.000000,0.747204,0.700522,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6162,27,31,57.142857,28.571429,28.571429,60.010531,32.362582,9.70,9.38,13.66,...,-11.0,-270.0,0.270270,0.840000,0.600846,2,0,0,0,1
6163,22,27,50.000000,21.428571,28.571429,60.209998,32.914628,7.65,8.84,11.79,...,-12.0,-271.0,0.000000,0.737470,0.527673,2,0,0,0,1
6164,19,22,42.857143,14.285714,28.571429,64.329611,43.550592,8.95,9.06,10.30,...,-21.0,-280.0,0.769231,0.632107,0.551759,0,0,0,1,0
6165,19,19,100.000000,7.142857,92.857143,69.027764,54.130755,13.55,10.36,10.55,...,-33.0,-292.0,1.000000,0.733010,0.591584,0,0,0,1,0
6166,19,19,92.857143,0.000000,92.857143,65.157180,45.524973,11.45,10.16,9.68,...,-28.0,-288.0,1.000000,0.687500,0.593936,0,0,0,1,0

In [54]:
from sklearn.preprocessing import StandardScaler

In [56]:
scaler = StandardScaler()

In [57]:
X = df_dummies.drop(["target_obj_20","target_obj_90"], axis = 1)
y = df_dummies["target_obj_50"]
X_train , X_test, y_train, y_test = train_test_split(X, y , test_size = 0.25, shuffle = False)

In [59]:
normalized_x_train = pd.DataFrame(scaler.fit_transform(X_train), columns = X_train.columns)

In [62]:
normalized_x_train

,ind_5,ind_6,ind_8,ind_9,ind_10,ind_12,ind_13,ind_14,ind_15,ind_16,...,ind_416,ind_418,ind_420,ind_422,ind_424,ind_426,ind_428,target_obj_50,GREEN,RED
0,0.870127,0.781126,1.436763,1.024034,0.247299,1.881432,1.203828,1.817472,1.043476,0.007093,...,-2.831841,-1.123430,-1.758399,-2.003547,1.199985,-0.007752,1.400109,1.129932,0.996331,-0.996331
1,1.091846,0.869810,1.436763,0.827481,0.365860,2.038731,1.258206,-0.036989,1.138631,0.107391,...,-3.236774,-1.378396,-1.816870,-2.060533,1.199985,0.162440,1.325720,1.129932,0.996331,-0.996331
2,1.357909,1.091522,1.436763,0.630927,0.484421,2.109841,1.281880,-0.442418,1.085767,0.119672,...,-3.425743,-1.378396,-1.836361,-2.089026,1.199985,0.507230,1.340546,1.129932,0.996331,-0.996331
3,1.668316,1.357576,1.436763,0.434373,0.602981,2.236302,1.322662,-0.585069,0.539504,0.187220,...,-3.655206,-1.590868,-1.894832,-2.136515,1.199985,0.711896,1.208730,0.084954,0.996331,-0.996331
4,1.845692,1.667973,1.436763,0.237819,0.721542,2.641415,1.442960,0.481059,0.039056,0.522911,...,-4.870007,-2.483249,-2.089736,-2.335968,1.199985,1.090273,1.390811,-0.960024,0.996331,-0.996331
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4620,-0.947971,-0.992569,-1.320265,0.237819,-0.938310,-0.863202,-0.603380,-0.299767,0.782679,1.493139,...,0.515611,0.193894,1.486754,0.988251,-0.916089,-0.066024,-0.954919,1.129932,0.996331,-0.996331
4621,-0.992315,-0.948227,-1.320265,0.041266,-0.819749,-0.337109,-0.051137,0.248312,0.772106,1.548405,...,0.515611,-0.273544,1.369811,0.874277,1.089979,0.177414,-0.654970,1.129932,0.996331,-0.996331
4622,-0.992315,-0.992569,0.452110,-0.155288,0.365860,0.240515,0.399972,0.946551,0.546552,1.532030,...,0.515611,-0.910959,1.223633,0.731811,1.199985,0.976732,-0.193534,-0.960024,0.996331,-0.996331
4623,-0.814939,-0.992569,0.255180,-0.351842,0.365860,0.089704,0.294275,0.496074,0.254037,1.403075,...,0.515611,-0.740982,1.252869,0.769802,1.199985,0.942069,-0.218758,0.084954,0.996331,-0.996331
4624,-0.548876,-0.815200,0.058249,-0.548396,0.365860,0.391413,0.498578,-0.142101,0.331571,1.184058,...,0.515611,-1.123430,1.174907,0.684322,1.199985,1.348397,-0.198910,-0.960024,0.996331,-0.996331

In [67]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

In [74]:
minmax_x_train = pd.DataFrame(scaler.fit_transform(X_train), columns = X_train.columns)

In [75]:
minmax_x_train

,ind_5,ind_6,ind_8,ind_9,ind_10,ind_12,ind_13,ind_14,ind_15,ind_16,...,ind_416,ind_418,ind_420,ind_422,ind_424,ind_426,ind_428,target_obj_50,GREEN,RED
0,0.632258,0.619355,1.000000,0.857143,0.571429,0.822644,0.964272,0.273510,0.297660,0.263739,...,0.511811,0.712766,0.214539,0.123162,1.000000,0.498547,0.787736,1.0,1.0,0.0
1,0.664516,0.632258,1.000000,0.785714,0.607143,0.849868,0.970535,0.121696,0.308017,0.277988,...,0.452756,0.680851,0.203901,0.112132,1.000000,0.537088,0.773630,1.0,1.0,0.0
2,0.703226,0.664516,1.000000,0.714286,0.642857,0.862175,0.973262,0.088506,0.302263,0.279732,...,0.425197,0.680851,0.200355,0.106618,1.000000,0.615169,0.776441,1.0,1.0,0.0
3,0.748387,0.703226,1.000000,0.642857,0.678571,0.884062,0.977959,0.076829,0.242808,0.289328,...,0.391732,0.654255,0.189716,0.097426,1.000000,0.661517,0.751445,0.5,1.0,0.0
4,0.774194,0.748387,1.000000,0.571429,0.714286,0.954177,0.991814,0.164106,0.188339,0.337017,...,0.214567,0.542553,0.154255,0.058824,1.000000,0.747204,0.785973,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4620,0.367742,0.361290,0.000000,0.571429,0.214286,0.347619,0.756129,0.100184,0.269275,0.474847,...,1.000000,0.877660,0.804965,0.702206,0.101124,0.485350,0.341153,1.0,1.0,0.0
4621,0.361290,0.367742,0.000000,0.500000,0.250000,0.438672,0.819733,0.145052,0.268124,0.482698,...,1.000000,0.819149,0.783688,0.680147,0.953271,0.540479,0.398033,1.0,1.0,0.0
4622,0.361290,0.361290,0.642857,0.428571,0.607143,0.538644,0.871689,0.202213,0.243575,0.480372,...,1.000000,0.739362,0.757092,0.652574,1.000000,0.721491,0.485534,0.0,1.0,0.0
4623,0.387097,0.361290,0.571429,0.357143,0.607143,0.512542,0.859515,0.165335,0.211738,0.462053,...,1.000000,0.760638,0.762411,0.659926,1.000000,0.713641,0.480751,0.5,1.0,0.0
4624,0.425806,0.387097,0.500000,0.285714,0.607143,0.564760,0.883046,0.113092,0.220176,0.430939,...,1.000000,0.712766,0.748227,0.643382,1.000000,0.805658,0.484515,0.0,1.0,0.0

In [76]:
mnb = MultinomialNB()

In [79]:
mnb_model = mnb.fit(minmax_x_train, y_train)
y_pred = mnb_model.predict(X_test)

ac = accuracy_score(y_test, y_pred)
con_matrix = confusion_matrix(y_test, y_pred) 
class_report = classification_report(y_test, y_pred)


print("Accuracy Score: {} \nConfusion Matrix: \n{}\n*********************************\nClassification Report\n{}".format(ac,con_matrix, class_report))

Accuracy Score: 0.20492866407263294
Confusion Matrix:
[[ 11 561 246]
 [  0  24   2]
 [  0 417 281]]
*********************************
Classification Report
              precision    recall  f1-score   support

           0       1.00      0.01      0.03       818
           1       0.02      0.92      0.05        26
           2       0.53      0.40      0.46       698

    accuracy                           0.20      1542
   macro avg       0.52      0.45      0.18      1542
weighted avg       0.77      0.20      0.22      1542